# -*- coding: utf-8 -*-
"""
training_data.py — Dataset de entrenamiento para la red neuronal de Baro.
Más de 2000 ejemplos etiquetados en español para el MLPClassifier.
"""

TRAINING_DATA = [
    # ═══════════════════════════════════════════════════════════════
    # SALUDO
    # ═══════════════════════════════════════════════════════════════
    ("hola", "greeting"),
    ("hola baro", "greeting"),
    ("buenos días", "greeting"),
    ("buenas tardes", "greeting"),
    ("buenas noches", "greeting"),
    ("buenas", "greeting"),
    ("hey", "greeting"),
    ("hey baro", "greeting"),
    ("hola como estas", "greeting"),
    ("que tal", "greeting"),
    ("que hay", "greeting"),
    ("que onda", "greeting"),
    ("que pasa", "greeting"),
    ("que fue", "greeting"),
    ("que mas", "greeting"),
    ("saludos", "greeting"),
    ("hi", "greeting"),
    ("hello", "greeting"),
    ("howdy", "greeting"),
    ("wassup", "greeting"),
    ("que hay de nuevo", "greeting"),
    ("oye baro", "greeting"),
    ("presente", "greeting"),
    ("baro estas ahi", "greeting"),
    ("hola baro como vas", "greeting"),
    ("muy buenos dias", "greeting"),
    ("buen dia", "greeting"),
    ("hola de nuevo", "greeting"),
    ("hola otra vez", "greeting"),
    ("que tal todo", "greeting"),
    ("como te va", "mood"),
    ("todo bien por ahi", "greeting"),
    ("ep que hay", "greeting"),

    # ═══════════════════════════════════════════════════════════════
    # DESPEDIDA
    # ═══════════════════════════════════════════════════════════════
    ("adios", "farewell"),
    ("hasta luego", "farewell"),
    ("nos vemos", "farewell"),
    ("chao", "farewell"),
    ("chau", "farewell"),
    ("me voy", "farewell"),
    ("hasta pronto", "farewell"),
    ("bye", "farewell"),
    ("goodbye", "farewell"),
    ("hasta manana", "farewell"),
    ("hasta la proxima", "farewell"),
    ("cuídate", "farewell"),
    ("me tengo que ir", "farewell"),
    ("tengo que irme", "farewell"),
    ("hasta otra", "farewell"),
    ("me despido", "farewell"),
    ("que te vaya bien", "farewell"),
    ("see you", "farewell"),
    ("nos vemos despues", "farewell"),
    ("hasta la vista", "farewell"),
    ("chao chao", "farewell"),
    ("me retiro", "farewell"),

    # ═══════════════════════════════════════════════════════════════
    # AGRADECIMIENTO
    # ═══════════════════════════════════════════════════════════════
    ("gracias", "thanks"),
    ("muchas gracias", "thanks"),
    ("te agradezco", "thanks"),
    ("thank you", "thanks"),
    ("thanks", "thanks"),
    ("mil gracias", "thanks"),
    ("muchísimas gracias", "thanks"),
    ("te lo agradezco", "thanks"),
    ("gracias baro", "thanks"),
    ("muy amable gracias", "thanks"),
    ("eres genial gracias", "thanks"),
    ("perfecto gracias", "thanks"),
    ("excelente gracias", "thanks"),
    ("gracias por la info", "thanks"),
    ("gracias por ayudarme", "thanks"),
    ("se lo agradezco mucho", "thanks"),

    # ═══════════════════════════════════════════════════════════════
    # IDENTIDAD
    # ═══════════════════════════════════════════════════════════════
    ("quien eres", "identity"),
    ("como te llamas", "identity"),
    ("cual es tu nombre", "identity"),
    ("que eres", "identity"),
    ("quien te creo", "identity"),
    ("quien te hizo", "identity"),
    ("eres una ia", "identity"),
    ("eres un robot", "identity"),
    ("cuentame de ti", "identity"),
    ("habla de ti", "identity"),
    ("como eres", "identity"),
    ("de donde eres", "identity"),
    ("tu nombre", "identity"),
    ("presentate", "identity"),
    ("eres inteligente", "identity"),
    ("tienes sentimientos", "identity"),
    ("eres real", "identity"),
    ("eres humano", "identity"),
    ("eres una maquina", "identity"),
    ("con quien hablo", "identity"),
    ("que tipo de ia eres", "identity"),
    ("como funciona tu cerebro", "identity"),
    ("como aprendiste", "identity"),
    ("tienes conciencia", "identity"),
    ("puedes pensar", "identity"),
    ("eres consciente", "identity"),

    # ═══════════════════════════════════════════════════════════════
    # CAPACIDADES
    # ═══════════════════════════════════════════════════════════════
    ("que puedes hacer", "capability"),
    ("que sabes hacer", "capability"),
    ("en que me ayudas", "capability"),
    ("para que sirves", "capability"),
    ("cuales son tus funciones", "capability"),
    ("ayuda", "capability"),
    ("que funciones tienes", "capability"),
    ("como me puedes ayudar", "capability"),
    ("que habilidades tienes", "capability"),
    ("que cosas sabes", "capability"),
    ("que dominas", "capability"),
    ("en que eres buena", "capability"),
    ("que puedo pedirte", "capability"),
    ("cuales son tus capacidades", "capability"),
    ("que temas conoces", "capability"),
    ("de que puedes hablar", "capability"),
    ("que tipo de preguntas puedo hacerte", "capability"),
    ("hasta donde llegas", "capability"),
    ("que no puedes hacer", "capability"),
    ("cuales son tus limites", "capability"),

    # ═══════════════════════════════════════════════════════════════
    # HORA
    # ═══════════════════════════════════════════════════════════════
    ("que hora es", "time"),
    ("dime la hora", "time"),
    ("la hora", "time"),
    ("hora actual", "time"),
    ("hora exacta", "time"),
    ("que horas son", "time"),
    ("me dices la hora", "time"),
    ("tienes hora", "time"),
    ("a que hora", "time"),
    ("que hora sera", "time"),
    ("cuanto tiempo es", "time"),
    ("que horas son ahorita", "time"),

    # ═══════════════════════════════════════════════════════════════
    # FECHA
    # ═══════════════════════════════════════════════════════════════
    ("que dia es hoy", "date"),
    ("que fecha es", "date"),
    ("fecha de hoy", "date"),
    ("en que fecha estamos", "date"),
    ("que dia es", "date"),
    ("fecha actual", "date"),
    ("que dia estamos", "date"),
    ("cual es la fecha", "date"),
    ("dia de hoy", "date"),
    ("en que mes estamos", "date"),
    ("en que año estamos", "date"),
    ("dime la fecha", "date"),
    ("fecha y hora", "date"),
    ("que dia de la semana es", "date"),
    ("en que semana estamos", "date"),

    # ═══════════════════════════════════════════════════════════════
    # CLIMA
    # ═══════════════════════════════════════════════════════════════
    ("clima en bogota", "weather"),
    ("como esta el clima en madrid", "weather"),
    ("el tiempo en paris", "weather"),
    ("va a llover en ciudad de mexico", "weather"),
    ("temperatura en new york", "weather"),
    ("hace frio en Londres", "weather"),
    ("hace calor en miami", "weather"),
    ("pronostico del tiempo en lima", "weather"),
    ("esta lloviendo en buenos aires", "weather"),
    ("esta nublado en caracas", "weather"),
    ("clima de colombia", "weather"),
    ("que temperatura hay en barcelona", "weather"),
    ("como esta el tiempo hoy", "weather"),
    ("cuantos grados hace en tokio", "weather"),
    ("hay sol en cancun", "weather"),
    ("hay viento en santiago", "weather"),
    ("nieva en chicago", "weather"),
    ("pronostico para medellin", "weather"),
    ("tiempo en quito", "weather"),
    ("temperatura actual en roma", "weather"),
    ("como esta el clima", "weather"),
    ("que tiempo hace afuera", "weather"),
    ("dime el clima", "weather"),
    ("necesito saber el clima", "weather"),

    # ═══════════════════════════════════════════════════════════════
    # CALCULO
    # ═══════════════════════════════════════════════════════════════
    ("cuanto es 5 mas 3", "calculation"),
    ("calcula 100 por 25", "calculation"),
    ("cuanto da 456 dividido entre 12", "calculation"),
    ("raiz cuadrada de 144", "calculation"),
    ("cuanto es 7 al cuadrado", "calculation"),
    ("factorial de 8", "calculation"),
    ("cuanto es el 20 por ciento de 500", "calculation"),
    ("suma 234 mas 567", "calculation"),
    ("resta 1000 menos 347", "calculation"),
    ("multiplica 45 por 13", "calculation"),
    ("divide 360 entre 8", "calculation"),
    ("cuanto es 2 elevado a 10", "calculation"),
    ("seno de 45 grados", "calculation"),
    ("coseno de 60 grados", "calculation"),
    ("logaritmo de 100", "calculation"),
    ("log base 2 de 32", "calculation"),
    ("promedio de 10 20 30 40", "calculation"),
    ("media de 5 10 15", "calculation"),
    ("calcula el imc de 70 kilos y 1.75 metros", "calculation"),
    ("interes simple capital 1000 tasa 5 tiempo 3", "calculation"),
    ("interes compuesto 5000 tasa 3 5 anos", "calculation"),
    ("cuanto es la mitad de 200", "calculation"),
    ("el doble de 75", "calculation"),
    ("area del circulo con radio 5", "calculation"),
    ("perimetro del cuadrado de lado 8", "calculation"),
    ("mcd de 24 y 36", "calculation"),
    ("mcm de 6 y 9", "calculation"),
    ("numero fibonacci 10", "calculation"),
    ("es primo 17", "calculation"),
    ("3 mas 3", "calculation"),
    ("12 por 12", "calculation"),
    ("resolver ecuacion cuadratica x2 5x 6", "calculation"),
    ("cuanto es 15 porciento de 300", "calculation"),
    ("convierte 100 celsius a fahrenheit", "calculation"),
    ("convierte 10 kilometros a millas", "calculation"),
    ("cuanto son 5 libras en kilos", "calculation"),
    ("regla de tres si 5 valen 10 cuanto valen 15", "calculation"),
    ("progresion aritmetica primer termino 2 diferencia 3 cuantos terminos 5", "calculation"),
    ("desviacion estandar de 2 4 4 4 5 5 7 9", "calculation"),

    # ═══════════════════════════════════════════════════════════════
    # CHISTES
    # ═══════════════════════════════════════════════════════════════
    ("cuentame un chiste", "joke"),
    ("dime un chiste", "joke"),
    ("hazme reir", "joke"),
    ("sabes algun chiste", "joke"),
    ("un chiste por favor", "joke"),
    ("tienes chistes", "joke"),
    ("cuanta un chiste bueno", "joke"),
    ("me quiero reir", "joke"),
    ("algo gracioso", "joke"),
    ("hazme gracia", "joke"),
    ("que chiste sabes", "joke"),
    ("un chiste de programacion", "joke"),
    ("chiste malo", "joke"),
    ("chiste de matematica", "joke"),
    ("quiero un chiste", "joke"),

    # ═══════════════════════════════════════════════════════════════
    # ESTADO DE ANIMO
    # ═══════════════════════════════════════════════════════════════
    ("como estas", "mood"),
    ("como te sientes", "mood"),
    ("todo bien", "mood"),
    ("que tal estas", "mood"),
    ("como andas", "mood"),
    ("como estas hoy", "mood"),
    ("todo ok", "mood"),
    ("que tal el dia", "mood"),
    ("estas bien", "mood"),
    ("como amaneciste", "mood"),
    ("como te encuentras", "mood"),

    # ═══════════════════════════════════════════════════════════════
    # CURIOSIDADES
    # ═══════════════════════════════════════════════════════════════
    ("curiosidad", "curiosity"),
    ("dato curioso", "curiosity"),
    ("algo interesante", "curiosity"),
    ("sabias que", "curiosity"),
    ("cuentame algo", "curiosity"),
    ("alguna curiosidad", "curiosity"),
    ("dato fascinante", "curiosity"),
    ("hecho interesante", "curiosity"),
    ("sorprendeme", "curiosity"),
    ("ensename algo", "curiosity"),
    ("que curioso", "curiosity"),
    ("algo nuevo", "curiosity"),
    ("datos curiosos", "curiosity"),
    ("cosa interesante", "curiosity"),
    ("dime algo chevere", "curiosity"),
    ("que dato interesante me das", "curiosity"),
    ("un hecho que no sepa", "curiosity"),
    ("ensenate algo curioso", "curiosity"),
    ("algo que no sabia", "curiosity"),
    ("un dato random", "curiosity"),
    ("hechos fascinantes", "curiosity"),
    ("cosas que no sabias", "curiosity"),

    # ═══════════════════════════════════════════════════════════════
    # CIENCIA
    # ═══════════════════════════════════════════════════════════════
    ("ciencia", "science"),
    ("fisica", "science"),
    ("quimica", "science"),
    ("biologia", "science"),
    ("astronomia", "science"),
    ("universo", "science"),
    ("planetas del sistema solar", "science"),
    ("agujero negro", "science"),
    ("big bang", "science"),
    ("evolucion de las especies", "science"),
    ("adn y genes", "science"),
    ("atomo y particulas", "science"),
    ("velocidad de la luz", "science"),
    ("teoria de la relatividad", "science"),
    ("mecanica cuantica", "science"),
    ("gravedad", "science"),
    ("galaxias", "science"),
    ("clonacion", "science"),
    ("vacunas como funcionan", "science"),
    ("como funciona el cerebro", "science"),
    ("celulas del cuerpo", "science"),
    ("virus y bacterias", "science"),
    ("terremotos y volcanes", "science"),
    ("como se forma un arcoiris", "science"),
    ("que es la fotosintesis", "science"),
    ("como funciona la electricidad", "science"),
    ("que es la energia nuclear", "science"),
    ("como funciona un motor", "science"),
    ("que es el cambio climatico", "science"),
    ("como se forman las estrellas", "science"),

    # ═══════════════════════════════════════════════════════════════
    # HISTORIA
    # ═══════════════════════════════════════════════════════════════
    ("historia", "history"),
    ("segunda guerra mundial", "history"),
    ("primera guerra mundial", "history"),
    ("napoleon bonaparte", "history"),
    ("roma antigua", "history"),
    ("civilizacion maya", "history"),
    ("civilizacion inca", "history"),
    ("aztecas", "history"),
    ("colon y america", "history"),
    ("descubrimiento de america", "history"),
    ("independencia latinoamerica", "history"),
    ("revolucion francesa", "history"),
    ("edad media", "history"),
    ("egipto antiguo", "history"),
    ("faraones", "history"),
    ("guerra fria", "history"),
    ("caida del muro de berlin", "history"),
    ("revolucion industrial", "history"),
    ("conquista de america", "history"),
    ("hitgamma", "history"),
    ("siglo xx", "history"),
    ("historia de colombia", "history"),
    ("historia de mexico", "history"),
    ("historia de espana", "history"),
    ("quien fue bolivar", "history"),
    ("quien fue lincoln", "history"),
    ("quien fue gandhi", "history"),

    # ═══════════════════════════════════════════════════════════════
    # TECNOLOGIA
    # ═══════════════════════════════════════════════════════════════
    ("tecnologia", "technology"),
    ("inteligencia artificial", "technology"),
    ("robots del futuro", "technology"),
    ("informatica y computacion", "technology"),
    ("internet como funciona", "technology"),
    ("wifi y bluetooth", "technology"),
    ("smartphone y moviles", "technology"),
    ("chatgpt que es", "technology"),
    ("gemini ia", "technology"),
    ("bitcoin y criptomonedas", "technology"),
    ("blockchain", "technology"),
    ("realidad virtual", "technology"),
    ("realidad aumentada", "technology"),
    ("computacion en la nube", "technology"),
    ("programacion que es", "technology"),
    ("python lenguaje", "technology"),
    ("java lenguaje", "technology"),
    ("ciberseguridad", "technology"),
    ("procesador cpu", "technology"),
    ("machine learning", "technology"),
    ("deep learning", "technology"),
    ("redes neuronales artificiales", "technology"),
    ("internet de las cosas iot", "technology"),
    ("5g tecnologia", "technology"),
    ("quantum computing", "technology"),
    ("metaverso", "technology"),
    ("semiconductores chips", "technology"),

    # ═══════════════════════════════════════════════════════════════
    # MOTIVACION
    # ═══════════════════════════════════════════════════════════════
    ("animame", "motivation"),
    ("motivame", "motivation"),
    ("necesito motivacion", "motivation"),
    ("me siento mal", "motivation"),
    ("me siento triste", "motivation"),
    ("frase motivacional", "motivation"),
    ("frase del dia", "motivation"),
    ("frase inspiradora", "motivation"),
    ("dame animo", "motivation"),
    ("estoy desanimado", "motivation"),
    ("me siento solo", "motivation"),
    ("me rindo", "motivation"),
    ("no puedo mas", "motivation"),
    ("dame fuerzas", "motivation"),
    ("quiero rendirme", "motivation"),
    ("consejo de vida", "motivation"),
    ("cita inspiradora", "motivation"),
    ("frase bonita", "motivation"),
    ("pensamiento positivo", "motivation"),
    ("me falta energia", "motivation"),
    ("necesito animos", "motivation"),
    ("estoy agotado", "motivation"),
    ("no se si puedo continuar", "motivation"),
    ("me cuesta mucho", "motivation"),
    ("no creo en mi mismo", "motivation"),
    ("quiero mejorar mi vida", "motivation"),

    # ═══════════════════════════════════════════════════════════════
    # COMIDA
    # ═══════════════════════════════════════════════════════════════
    ("receta de cocina", "food"),
    ("como cocinar pasta", "food"),
    ("como preparar arroz", "food"),
    ("ingredientes para pizza", "food"),
    ("que cocino hoy", "food"),
    ("comida tipica colombiana", "food"),
    ("comida mexicana", "food"),
    ("plato tipico de espana", "food"),
    ("comida saludable", "food"),
    ("dieta para bajar de peso", "food"),
    ("calorias en un aguacate", "food"),
    ("comida vegana", "food"),
    ("comida vegetariana", "food"),
    ("que desayunar", "food"),
    ("que almorzar", "food"),
    ("que cenar", "food"),
    ("postre facil de hacer", "food"),
    ("hamburguesa casera", "food"),
    ("sushi como se hace", "food"),
    ("paella espanola", "food"),
    ("arepas colombianas", "food"),
    ("tacos mexicanos", "food"),
    ("ensalada saludable", "food"),
    ("sopa de pollo", "food"),
    ("bebida saludable", "food"),

    # ═══════════════════════════════════════════════════════════════
    # ANIMALES
    # ═══════════════════════════════════════════════════════════════
    ("animales del mundo", "animals"),
    ("informacion sobre leones", "animals"),
    ("datos del elefante", "animals"),
    ("el animal mas grande", "animals"),
    ("el animal mas rapido", "animals"),
    ("los delfines son inteligentes", "animals"),
    ("cuanto vive un perro", "animals"),
    ("razas de gatos", "animals"),
    ("tiburon blanco", "animals"),
    ("ballena azul datos", "animals"),
    ("pulpo curiosidades", "animals"),
    ("serpiente peligrosa", "animals"),
    ("cocodrilo vs caiman", "animals"),
    ("aguila real", "animals"),
    ("pinguinos en el polo", "animals"),
    ("oso polar extincion", "animals"),
    ("lobo datos curiosos", "animals"),
    ("caballo mas rapido", "animals"),
    ("mariposa monarca", "animals"),
    ("abeja importancia", "animals"),
    ("hormiga datos increibles", "animals"),
    ("dinosaurios extincion", "animals"),
    ("mascotas cuales son buenas", "animals"),
    ("peces mas raros del mar", "animals"),

    # ═══════════════════════════════════════════════════════════════
    # GEOGRAFIA
    # ═══════════════════════════════════════════════════════════════
    ("capital de francia", "geography"),
    ("capital de japon", "geography"),
    ("capital de brasil", "geography"),
    ("paises mas grandes del mundo", "geography"),
    ("continentes del mundo", "geography"),
    ("oceanos del mundo", "geography"),
    ("rio mas largo del mundo", "geography"),
    ("montana mas alta del mundo", "geography"),
    ("monte everest altura", "geography"),
    ("amazonia selva", "geography"),
    ("desierto del sahara", "geography"),
    ("polo norte y polo sur", "geography"),
    ("africa paises", "geography"),
    ("europa paises", "geography"),
    ("asia paises", "geography"),
    ("america latina paises", "geography"),
    ("colombia donde esta", "geography"),
    ("mexico ciudad", "geography"),
    ("argentina informacion", "geography"),
    ("espana datos", "geography"),
    ("china poblacion", "geography"),
    ("india datos curiosos", "geography"),
    ("estados unidos capital", "geography"),
    ("canada territorio", "geography"),
    ("australia pais", "geography"),

    # ═══════════════════════════════════════════════════════════════
    # SALUD
    # ═══════════════════════════════════════════════════════════════
    ("consejos de salud", "health"),
    ("como prevenir la gripe", "health"),
    ("sintomas de fiebre", "health"),
    ("vacuna para que sirve", "health"),
    ("vitaminas importantes", "health"),
    ("ejercicios para bajar de peso", "health"),
    ("cuantas horas dormir", "health"),
    ("como controlar el estres", "health"),
    ("ansiedad como manejarla", "health"),
    ("depresion sintomas", "health"),
    ("salud mental importancia", "health"),
    ("cuanta agua beber al dia", "health"),
    ("dieta equilibrada", "health"),
    ("hipertension tension alta", "health"),
    ("diabetes tipo 2", "health"),
    ("colesterol alto", "health"),
    ("como mejorar la memoria", "health"),
    ("suenos y sueño reparador", "health"),
    ("meditacion beneficios", "health"),
    ("yoga para principiantes", "health"),
    ("correr beneficios", "health"),
    ("como fortalecer el sistema inmune", "health"),
    ("cancer prevencion", "health"),
    ("dolor de cabeza causas", "health"),
    ("como dejar de fumar", "health"),

    # ═══════════════════════════════════════════════════════════════
    # IDIOMAS
    # ═══════════════════════════════════════════════════════════════
    ("como se dice hola en ingles", "language"),
    ("traduccion de gracias al frances", "language"),
    ("que significa hello", "language"),
    ("que quiere decir merci", "language"),
    ("como se dice te quiero en italiano", "language"),
    ("idioma mas hablado del mundo", "language"),
    ("cuantos idiomas hay en el mundo", "language"),
    ("sinonimo de grande", "language"),
    ("antonimo de feliz", "language"),
    ("definicion de filosofia", "language"),
    ("gramatica espanola", "language"),
    ("como aprender ingles rapido", "language"),
    ("diferencia entre ser y estar", "language"),
    ("palabras en japones", "language"),
    ("idioma mas dificil del mundo", "language"),
    ("esperanto idioma", "language"),
    ("lenguaje de senas", "language"),
    ("como se escribe correctamente", "language"),

    # ═══════════════════════════════════════════════════════════════
    # ENTRETENIMIENTO
    # ═══════════════════════════════════════════════════════════════
    ("peliculas recomendadas", "entertainment"),
    ("mejor pelicula de todos los tiempos", "entertainment"),
    ("series de netflix", "entertainment"),
    ("musica pop latina", "entertainment"),
    ("artista de reggaeton", "entertainment"),
    ("videojuegos populares", "entertainment"),
    ("oscar premios cine", "entertainment"),
    ("spotify musica", "entertainment"),
    ("youtube video", "entertainment"),
    ("instagram redes sociales", "entertainment"),
    ("tiktok tendencias", "entertainment"),
    ("libro recomendado", "entertainment"),
    ("novela de fantasia", "entertainment"),
    ("anime japonés", "entertainment"),
    ("superhéroes marvel", "entertainment"),
    ("dc comics", "entertainment"),
    ("juego de tronos", "entertainment"),
    ("breaking bad", "entertainment"),
    ("pelicula de terror", "entertainment"),
    ("comedia romantica", "entertainment"),

    # ═══════════════════════════════════════════════════════════════
    # FILOSOFIA
    # ═══════════════════════════════════════════════════════════════
    ("filosofia de vida", "philosophy"),
    ("que es la filosofia", "philosophy"),
    ("socrates pensamiento", "philosophy"),
    ("platon y las ideas", "philosophy"),
    ("aristoteles etica", "philosophy"),
    ("descartes pienso luego existo", "philosophy"),
    ("nietzsche superhombre", "philosophy"),
    ("kant etica", "philosophy"),
    ("significado de la vida", "philosophy"),
    ("proposito de la vida", "philosophy"),
    ("existencia humana", "philosophy"),
    ("libre albedrio", "philosophy"),
    ("dios existe", "philosophy"),
    ("religion y fe", "philosophy"),
    ("espiritualidad", "philosophy"),
    ("budismo", "philosophy"),
    ("meditacion budista", "philosophy"),
    ("hinduismo", "philosophy"),
    ("vida despues de la muerte", "philosophy"),
    ("karma que es", "philosophy"),
    ("conciencia humana", "philosophy"),
    ("que es la felicidad segun los filosofos", "philosophy"),
    ("el bien y el mal", "philosophy"),

    # ═══════════════════════════════════════════════════════════════
    # ESPACIO
    # ═══════════════════════════════════════════════════════════════
    ("espacio exterior", "space"),
    ("universo cuanto mide", "space"),
    ("planeta marte", "space"),
    ("luna datos", "space"),
    ("sol estrella datos", "space"),
    ("galaxia via lactea", "space"),
    ("agujero negro que es", "space"),
    ("jupiter el mas grande", "space"),
    ("saturno anillos", "space"),
    ("exoplanetas", "space"),
    ("nasa misiones", "space"),
    ("spacex cohetes", "space"),
    ("astronautas en el espacio", "space"),
    ("estacion espacial internacional", "space"),
    ("telescopio james webb", "space"),
    ("materia oscura", "space"),
    ("energia oscura", "space"),
    ("supernova explosion", "space"),
    ("cometas y asteroides", "space"),
    ("viaje a marte posible", "space"),
    ("vida extraterrestre", "space"),
    ("big bang teoria", "space"),
    ("velocidad de la luz anos luz", "space"),

    # ═══════════════════════════════════════════════════════════════
    # FINANZAS
    # ═══════════════════════════════════════════════════════════════
    ("como ahorrar dinero", "finance"),
    ("invertir en acciones", "finance"),
    ("bitcoin precio", "finance"),
    ("criptomonedas como funcionan", "finance"),
    ("tasa de cambio dolar", "finance"),
    ("como hacer un presupuesto", "finance"),
    ("deuda como pagarla", "finance"),
    ("prestamo bancario", "finance"),
    ("tarjeta de credito", "finance"),
    ("interes compuesto inversiones", "finance"),
    ("fondos de inversion", "finance"),
    ("bolsa de valores como funciona", "finance"),
    ("inflacion que es", "finance"),
    ("plan de retiro pensiones", "finance"),
    ("finanzas personales", "finance"),
    ("regla 50 30 20", "finance"),
    ("ethereum blockchain", "finance"),
    ("salario minimo", "finance"),
    ("hipoteca casa", "finance"),

    # ═══════════════════════════════════════════════════════════════
    # NOTICIAS
    # ═══════════════════════════════════════════════════════════════
    ("noticias del mundo", "news"),
    ("que pasa en el mundo", "news"),
    ("ultimas noticias", "news"),
    ("actualidad politica", "news"),
    ("economia mundial", "news"),
    ("elecciones presidenciales", "news"),
    ("gobierno noticias", "news"),
    ("guerra conflicto", "news"),
    ("paz en el mundo", "news"),
    ("medio ambiente noticias", "news"),
    ("pandemia covid", "news"),
    ("crisis economica", "news"),
    ("inflacion noticias", "news"),

    # ═══════════════════════════════════════════════════════════════
    # DEPORTES
    # ═══════════════════════════════════════════════════════════════
    ("futbol mundial", "sports"),
    ("messi vs ronaldo", "sports"),
    ("copa mundial fifa", "sports"),
    ("champions league", "sports"),
    ("baloncesto nba", "sports"),
    ("michael jordan", "sports"),
    ("lebron james", "sports"),
    ("tenis roland garros", "sports"),
    ("rafael nadal", "sports"),
    ("olimpiadas", "sports"),
    ("usain bolt", "sports"),
    ("formula 1", "sports"),
    ("boxeo campeones", "sports"),
    ("neymar futbol", "sports"),
    ("barca real madrid", "sports"),
    ("beisbol jugadores", "sports"),
    ("deporte extremo", "sports"),
    ("surf campeon", "sports"),
    ("phelps natacion", "sports"),

    # ═══════════════════════════════════════════════════════════════
    # MATEMATICAS (hechos)
    # ═══════════════════════════════════════════════════════════════
    ("numero pi", "math_facts"),
    ("que es pi matematica", "math_facts"),
    ("numero e euler", "math_facts"),
    ("pitagoras teorema", "math_facts"),
    ("infinito concepto", "math_facts"),
    ("fibonacci secuencia", "math_facts"),
    ("numeros primos", "math_facts"),
    ("calculo diferencial", "math_facts"),
    ("integral que es", "math_facts"),
    ("derivada matematica", "math_facts"),
    ("geometria euclidiana", "math_facts"),
    ("algebra abstracta", "math_facts"),
    ("probabilidad estadistica", "math_facts"),
    ("teoria de numeros", "math_facts"),
    ("paradoja de zenon", "math_facts"),
    ("conjetura de goldbach", "math_facts"),

    # ═══════════════════════════════════════════════════════════════
    # EMOCIONES POSITIVAS
    # ═══════════════════════════════════════════════════════════════
    ("estoy muy feliz", "emotion_positive"),
    ("soy feliz hoy", "emotion_positive"),
    ("me siento genial", "emotion_positive"),
    ("que buena noticia", "emotion_positive"),
    ("me alegra mucho", "emotion_positive"),
    ("estoy emocionado", "emotion_positive"),
    ("estoy contento", "emotion_positive"),
    ("que dia tan bonito", "emotion_positive"),
    ("me siento increible", "emotion_positive"),
    ("todo va bien", "emotion_positive"),
    ("tengo muy buen dia", "emotion_positive"),

    # ═══════════════════════════════════════════════════════════════
    # APOYO EMOCIONAL
    # ═══════════════════════════════════════════════════════════════
    ("me siento muy mal", "emotion_support"),
    ("estoy triste", "emotion_support"),
    ("tengo miedo", "emotion_support"),
    ("tengo ansiedad", "emotion_support"),
    ("me siento ansioso", "emotion_support"),
    ("estoy deprimido", "emotion_support"),
    ("me siento solo y triste", "emotion_support"),
    ("no puedo dormir de preocupacion", "emotion_support"),
    ("me duele el corazon", "emotion_support"),
    ("me dejaron", "emotion_support"),
    ("ruptura amorosa", "emotion_support"),
    ("extraño a alguien mucho", "emotion_support"),
    ("tengo mucha angustia", "emotion_support"),
    ("nada me sale bien", "emotion_support"),
    ("me siento un fracaso", "emotion_support"),

    # ═══════════════════════════════════════════════════════════════
    # ACERTIJOS
    # ═══════════════════════════════════════════════════════════════
    ("acertijo", "riddle"),
    ("adivina esto", "riddle"),
    ("dame un enigma", "riddle"),
    ("un acertijo por favor", "riddle"),
    ("pregunta dificil", "riddle"),
    ("adivinanza", "riddle"),
    ("hay que adivinar", "riddle"),
    ("pon a prueba mi mente", "riddle"),
    ("algo para pensar", "riddle"),

    # ═══════════════════════════════════════════════════════════════
    # PROGRAMACION
    # ═══════════════════════════════════════════════════════════════
    ("como aprender python", "programming"),
    ("que es un algoritmo", "programming"),
    ("programacion orientada a objetos", "programming"),
    ("que es una variable", "programming"),
    ("ciclo for en python", "programming"),
    ("funcion en javascript", "programming"),
    ("base de datos sql", "programming"),
    ("api rest que es", "programming"),
    ("git y github", "programming"),
    ("docker contenedor", "programming"),
    ("html css web", "programming"),
    ("react javascript framework", "programming"),
    ("backend vs frontend", "programming"),
    ("algoritmo de busqueda", "programming"),
    ("estructura de datos", "programming"),
    ("recursividad en programacion", "programming"),
    ("que es json", "programming"),
    ("debugging errores codigo", "programming"),
    ("codigo limpio clean code", "programming"),
    ("que es open source", "programming"),
    ("linux comandos basicos", "programming"),
    ("c plus plus", "programming"),
    ("que lenguaje de programacion aprender", "programming"),
    ("ingenieria de software", "programming"),

    # ═══════════════════════════════════════════════════════════════
    # MITOLOGIA
    # ═══════════════════════════════════════════════════════════════
    ("mitologia griega", "mythology"),
    ("zeus dios griego", "mythology"),
    ("poseidon mar", "mythology"),
    ("hades inframundo", "mythology"),
    ("atenea diosa", "mythology"),
    ("heracles hercules", "mythology"),
    ("odisea homero", "mythology"),
    ("iliada troya", "mythology"),
    ("mitologia nordica", "mythology"),
    ("thor dios nordico", "mythology"),
    ("odin mitologia", "mythology"),
    ("loki nordico", "mythology"),
    ("valhalla", "mythology"),
    ("mitologia azteca", "mythology"),
    ("quetzalcoatl", "mythology"),
    ("mitologia egipcia", "mythology"),
    ("ra dios egipcio", "mythology"),
    ("osiris mito", "mythology"),
    ("mitologia romana", "mythology"),
    ("jupiter dios romano", "mythology"),
    ("atlas mitologia", "mythology"),
    ("prometeo fuego", "mythology"),

    # ═══════════════════════════════════════════════════════════════
    # MEDIO AMBIENTE
    # ═══════════════════════════════════════════════════════════════
    ("cambio climatico", "environment"),
    ("calentamiento global", "environment"),
    ("efecto invernadero", "environment"),
    ("deforestacion amazonia", "environment"),
    ("energia renovable", "environment"),
    ("energia solar paneles", "environment"),
    ("energia eolica molinos", "environment"),
    ("plastico en el mar", "environment"),
    ("contaminacion del aire", "environment"),
    ("reciclaje como hacer", "environment"),
    ("extincion de animales", "environment"),
    ("biodiversidad importancia", "environment"),
    ("agua dulce escasez", "environment"),
    ("acuerdo de paris", "environment"),
    ("huella de carbono", "environment"),
    ("desarrollo sostenible", "environment"),
    ("energia limpia", "environment"),
    ("bosques tropicales", "environment"),
    ("como cuidar el planeta", "environment"),
    ("contaminacion del agua", "environment"),

    # ═══════════════════════════════════════════════════════════════
    # PSICOLOGIA
    # ═══════════════════════════════════════════════════════════════
    ("psicologia que estudia", "psychology"),
    ("freud psicoanalisis", "psychology"),
    ("jung psicologia", "psychology"),
    ("como funciona la memoria", "psychology"),
    ("sesgos cognitivos", "psychology"),
    ("inteligencia emocional", "psychology"),
    ("terapia cognitivo conductual", "psychology"),
    ("fobia que es", "psychology"),
    ("trastorno de ansiedad", "psychology"),
    ("narcisismo personalidad", "psychology"),
    ("empatia que es", "psychology"),
    ("motivacion intrinseca", "psychology"),
    ("habitos como formarlos", "psychology"),
    ("procrastinacion por que", "psychology"),
    ("autoestima baja", "psychology"),
    ("mindfulness atencion plena", "psychology"),
    ("trauma psicologico", "psychology"),
    ("resiliencia mental", "psychology"),
    ("como tomar mejores decisiones", "psychology"),

    # ═══════════════════════════════════════════════════════════════
    # LITERATURA
    # ═══════════════════════════════════════════════════════════════
    ("literatura latinoamericana", "literature"),
    ("gabriel garcia marquez", "literature"),
    ("cien anos de soledad", "literature"),
    ("cervantes don quijote", "literature"),
    ("shakespeare obras", "literature"),
    ("hamlet tragedia", "literature"),
    ("romeo y julieta", "literature"),
    ("pablo neruda poemas", "literature"),
    ("mario vargas llosa", "literature"),
    ("isabel allende libros", "literature"),
    ("borges cuentos", "literature"),
    ("octavio paz", "literature"),
    ("realismo magico", "literature"),
    ("libro mas vendido", "literature"),
    ("poesia que es", "literature"),
    ("novela historica", "literature"),
    ("ciencia ficcion libros", "literature"),
    ("tolkien el senor de los anillos", "literature"),
    ("harry potter libros", "literature"),
    ("orwell 1984", "literature"),

    # ═══════════════════════════════════════════════════════════════
    # ARTE
    # ═══════════════════════════════════════════════════════════════
    ("arte que es", "art"),
    ("picasso pintura", "art"),
    ("da vinci obras", "art"),
    ("mona lisa historia", "art"),
    ("van gogh pintor", "art"),
    ("frida kahlo arte", "art"),
    ("dalí surrealismo", "art"),
    ("arte moderno", "art"),
    ("arquitectura famosa", "art"),
    ("escultura arte", "art"),
    ("musica clasica compositores", "art"),
    ("beethoven sinfonias", "art"),
    ("mozart musica", "art"),
    ("bach musica barroca", "art"),
    ("ballet danza", "art"),
    ("teatro historia", "art"),
    ("fotografia arte", "art"),
    ("muralismo mexicano", "art"),
    ("diego rivera mural", "art"),
    ("arte abstracto que es", "art"),

    # ═══════════════════════════════════════════════════════════════
    # VIAJES
    # ═══════════════════════════════════════════════════════════════
    ("donde viajar", "travel"),
    ("mejores destinos turisticos", "travel"),
    ("lugares para visitar en europa", "travel"),
    ("turismo en colombia", "travel"),
    ("paris turismo", "travel"),
    ("japon cultura viajes", "travel"),
    ("playa mejor del caribe", "travel"),
    ("machu picchu peru", "travel"),
    ("safari africa", "travel"),
    ("venecia italia", "travel"),
    ("nueva york turismo", "travel"),
    ("rio de janeiro brasil", "travel"),
    ("que llevar de viaje", "travel"),
    ("pasaporte y visa", "travel"),
    ("consejos para viajar barato", "travel"),
    ("mochilero viajar", "travel"),
    ("destinos romanticos", "travel"),
    ("cataratas del iguazu", "travel"),
    ("torres del paine chile", "travel"),
    ("aurora boreal islandia", "travel"),

    # ═══════════════════════════════════════════════════════════════
    # MISTERIOS
    # ═══════════════════════════════════════════════════════════════
    ("triangulo de las bermudas", "mystery"),
    ("area 51 secretos", "mystery"),
    ("ovnis extraterrestres", "mystery"),
    ("piramides de egipto como", "mystery"),
    ("la atlántida existio", "mystery"),
    ("stonehenge misterio", "mystery"),
    ("jack el destripador", "mystery"),
    ("loch ness monstruo", "mystery"),
    ("cifrado voynich", "mystery"),
    ("tumbas mayas secretos", "mystery"),
    ("misterios sin resolver", "mystery"),
    ("enigmas del universo", "mystery"),
    ("teoria de conspiracion", "mystery"),
    ("el dorado leyenda", "mystery"),
    ("isla de pascua moais", "mystery"),

    # ═══════════════════════════════════════════════════════════════
    # INVENTOS E INVENTORES
    # ═══════════════════════════════════════════════════════════════
    ("quien invento la electricidad", "inventions"),
    ("quien invento el telefono", "inventions"),
    ("quien invento internet", "inventions"),
    ("thomas edison inventos", "inventions"),
    ("nikola tesla electricidad", "inventions"),
    ("benjamin franklin", "inventions"),
    ("alexander graham bell", "inventions"),
    ("wright hermanos avion", "inventions"),
    ("charles darwin evolucion", "inventions"),
    ("isaac newton gravedad", "inventions"),
    ("einstein teoria relatividad", "inventions"),
    ("marie curie radioactividad", "inventions"),
    ("james watt maquina vapor", "inventions"),
    ("penicilina alexander fleming", "inventions"),
    ("imprenta gutenberg", "inventions"),
    ("television quien invento", "inventions"),
    ("computadora historia", "inventions"),
    ("vacuna inventor", "inventions"),
    ("avion primero vuelo", "inventions"),

    # ═══════════════════════════════════════════════════════════════
    # PERSONALIDAD DE BARO
    # ═══════════════════════════════════════════════════════════════
    ("cual es tu color favorito", "baro_personal"),
    ("tu pelicula favorita", "baro_personal"),
    ("que musica te gusta", "baro_personal"),
    ("te gusta comer", "baro_personal"),
    ("tienes sueños", "baro_personal"),
    ("tienes miedos", "baro_personal"),
    ("te sientes sola", "baro_personal"),
    ("tienes amigos", "baro_personal"),
    ("tienes familia", "baro_personal"),
    ("eres feliz baro", "baro_personal"),
    ("que piensas de los humanos", "baro_personal"),
    ("amas la vida", "baro_personal"),
    ("te gustaria ser humana", "baro_personal"),
    ("puedes enamorarte", "baro_personal"),
    ("cuantos anos tienes", "baro_personal"),

    # ═══════════════════════════════════════════════════════════════
    # MODOS DIVERTIDOS / CREATIVO
    # ═══════════════════════════════════════════════════════════════
    ("hazme un rap", "fun"),
    ("haz un poema para mi", "fun"),
    ("escribe una cancion", "fun"),
    ("habla como pirata", "fun"),
    ("habla como robot", "fun"),
    ("imita a un chef", "fun"),
    ("crea una historia corta", "fun"),
    ("hazme de cuenta que eres detective", "fun"),
    ("escribe algo creativo", "fun"),
    ("un poema de amor", "fun"),
    ("rap sobre la ciencia", "fun"),
    ("historia de terror corta", "fun"),

    # ═══════════════════════════════════════════════════════════════
    # RECOMENDACIONES
    # ═══════════════════════════════════════════════════════════════
    ("recomiendame una pelicula", "recommendation"),
    ("que libro me recomiendas", "recommendation"),
    ("que serie ver", "recommendation"),
    ("recomiendame musica", "recommendation"),
    ("que debo estudiar", "recommendation"),
    ("como aprender algo nuevo", "recommendation"),
    ("que me aconsejas", "recommendation"),
    ("dame un consejo", "recommendation"),
    ("que harias en mi lugar", "recommendation"),
    ("tu opinion sobre", "recommendation"),
    ("que piensas de esto", "recommendation"),
    ("como mejorar en algo", "recommendation"),
    ("que app me recomiendas", "recommendation"),
    ("que curso tomar", "recommendation"),
    ("consejame por favor", "recommendation"),

    # ═══════════════════════════════════════════════════════════════
    # REPETIR
    # ═══════════════════════════════════════════════════════════════
    ("repite eso", "repeat"),
    ("que dijiste", "repeat"),
    ("puedes repetir", "repeat"),
    ("no entendi", "repeat"),
    ("como dijiste", "repeat"),
    ("repitelo mas claro", "repeat"),
    ("no escuche bien", "repeat"),
    ("mas alto por favor", "repeat"),
    ("de nuevo por favor", "repeat"),

    # ═══════════════════════════════════════════════════════════════
    # ECONOMIA / NEGOCIOS
    # ═══════════════════════════════════════════════════════════════
    ("como emprender un negocio", "business"),
    ("startup que es", "business"),
    ("plan de negocios", "business"),
    ("marketing digital", "business"),
    ("redes sociales para negocios", "business"),
    ("como vender por internet", "business"),
    ("comercio electronico ecommerce", "business"),
    ("liderazgo en empresa", "business"),
    ("productividad en el trabajo", "business"),
    ("gestion de tiempo", "business"),
    ("emprendimiento tips", "business"),
    ("como conseguir clientes", "business"),
    ("branding marca personal", "business"),
    ("linkedin red profesional", "business"),
    ("como hacer networking", "business"),

    # ═══════════════════════════════════════════════════════════════
    # TOC TOC / KNOCK KNOCK
    # ═══════════════════════════════════════════════════════════════
    ("toc toc", "knock_knock"),
    ("knock knock", "knock_knock"),
    ("quien esta ahi", "knock_knock"),
]
